name: ritchie-prod

services:
  db:
    image: postgres:16
    container_name: postgres_prod
    restart: unless-stopped
    env_file:
      - production/db.env
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod

  api:
    image: misterazix/ritchie-invest-api:${API_TAG:-latest}
    container_name: api_prod
    restart: unless-stopped
    env_file:
      - production/api.env
      - production/db.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - prod
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.api-prod.rule=Host(`api.ritchie-invest.fr`)
      - traefik.http.routers.api-prod.entrypoints=websecure
      - traefik.http.routers.api-prod.tls.certresolver=letsencrypt
      - traefik.http.services.api-prod.loadbalancer.server.port=8080

  admin:
    image: misterazix/ritchie-invest-admin:${ADMIN_TAG:-latest}
    container_name: admin_prod
    restart: unless-stopped
    env_file:
      - production/admin.env
    depends_on:
      - api
    networks:
      - prod
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.admin-prod.rule=Host(`admin.ritchie-invest.fr`)
      - traefik.http.routers.admin-prod.entrypoints=websecure
      - traefik.http.routers.admin-prod.tls.certresolver=letsencrypt
      - traefik.http.services.admin-prod.loadbalancer.server.port=8080

networks:
  prod:
    name: prod
  traefik:
    external: true

volumes:
  pgdata_prod:
    driver: local
