name: ritchie-proxy

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # ---- HTTP to HTTPS ----
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # ---- Logs ----
      - --log.level=INFO              # (DEBUG, WARN, ERROR)
      - --log.format=json             # json ou common
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.bufferingsize=50  # flush après 50 lignes (stdout)
      # Garder tous les headers (sinon filtrer via accesslog.fields.*)
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=keep
      # Pour écrire dans des fichiers (décommenter + volume logs)
      # - --log.filepath=/var/log/traefik/traefik.log
      # - --accesslog.filepath=/var/log/traefik/access.log
      # - --accesslog.bufferingsize=0   # flush immédiat en mode fichier
      # ----------------
      # Dashboard
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      # Pour logs fichier (si activé ci-dessus)
      # - traefik_logs:/var/log/traefik
    networks:
      - traefik
    labels:
      # Activer Traefik pour ce service
      - traefik.enable=true
      # (Optionnel) Exposer le dashboard derrière un host dédié
      # - traefik.http.routers.traefik.rule=Host(`traefik.ritchie-invest.fr`)
      # - traefik.http.routers.traefik.entrypoints=websecure
      # - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      # - traefik.http.routers.traefik.service=api@internal

volumes:
  traefik_letsencrypt:
    driver: local
  # traefik_logs:
  #   driver: local

networks:
  traefik:
    name: traefik
